In [72]:
# Dependencies
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from tensorflow import keras

import tensorflow as tf

In [73]:
file = 'train.csv'

df = pd.read_csv(file)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [74]:

get_dummies_df = pd.get_dummies(df).dropna()

get_dummies_df

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,1,0,0,0,0,1,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,1,0,0,0,0,1,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,1,0,0,0,0,1,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,0,0,1,1,0,0,0,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,0,0,1,0,0,0,0,1,0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0,0,0,1,0,0,0,0,1,0
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,0,0,1,0,0,0,0,1,0
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0,0,0,1,0,0,0,0,1,0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0,0,0,1,0,0,0,0,1,0

In [75]:
get_dummies_df['GarageYrBlt'].dtypes

dtype('float64')

In [76]:
df['Neighborhood'].unique()

array(['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',
       'NWAmes', 'OldTown', 'BrkSide', 'Sawyer', 'NridgHt', 'NAmes',
       'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards', 'Timber', 'Gilbert',
       'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU',
       'Blueste'], dtype=object)

In [77]:

get_dummies_df["sales_price_bin"] = pd.qcut(get_dummies_df['SalePrice'], 10)

get_dummies_df

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,sales_price_bin
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,1,0,0,0,0,1,0,"(202900.0, 239000.0]"
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,1,0,0,0,0,1,0,"(180000.0, 202900.0]"
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,1,0,0,0,0,1,0,"(202900.0, 239000.0]"
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,0,1,1,0,0,0,0,0,"(136500.0, 148000.0]"
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,1,0,0,0,0,1,0,"(239000.0, 290000.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,0,1,0,0,0,0,1,0,"(164900.0, 180000.0]"
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0,0,1,0,0,0,0,1,0,"(202900.0, 239000.0]"
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,0,1,0,0,0,0,1,0,"(239000.0, 290000.0]"
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0,0,1,0,0,0,0,1,0,"(136500.0, 148000.0]"
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0,0,1,0,0,0,0,1,0,"(136500.0, 148000.0]"

In [78]:
get_dummies_df.dtypes

Id                          int64
MSSubClass                  int64
LotFrontage               float64
LotArea                     int64
OverallQual                 int64
                           ...
SaleCondition_Alloca        uint8
SaleCondition_Family        uint8
SaleCondition_Normal        uint8
SaleCondition_Partial       uint8
sales_price_bin          category
Length: 291, dtype: object

 RANFOM FOREST MODEL

In [79]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

le.fit(get_dummies_df['sales_price_bin'])

list(le.classes_)

[Interval(35310.999, 109500.0, closed='right'),
 Interval(109500.0, 125000.0, closed='right'),
 Interval(125000.0, 136500.0, closed='right'),
 Interval(136500.0, 148000.0, closed='right'),
 Interval(148000.0, 164900.0, closed='right'),
 Interval(164900.0, 180000.0, closed='right'),
 Interval(180000.0, 202900.0, closed='right'),
 Interval(202900.0, 239000.0, closed='right'),
 Interval(239000.0, 290000.0, closed='right'),
 Interval(290000.0, 755000.0, closed='right')]

In [80]:
y = le.fit_transform(get_dummies_df.sales_price_bin)

In [81]:
get_dummies_df.sales_price_bin = le.fit_transform(get_dummies_df.sales_price_bin)

In [82]:
y

array([7, 6, 7, ..., 8, 3, 3])

In [83]:
X = get_dummies_df

In [84]:
X = X.drop(columns=['sales_price_bin'])

In [85]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [86]:
import sklearn as skl
# Create scaler instance
X_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

RANDOM FOREST CLASSIFIER

In [87]:
#random forest  
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)
rf_model = rf_model.fit(X_train_scaled, y_train)
predictions = rf_model.predict(X_test_scaled)

In [88]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print("Confusion Matrix")
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix
Accuracy Score : 0.7615658362989324
Classification Report
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        28
           1       0.96      0.96      0.96        25
           2       0.79      0.61      0.69        31
           3       0.67      0.57      0.62        28
           4       0.58      0.75      0.65        24
           5       0.59      0.56      0.58        34
           6       0.50      0.75      0.60        20
           7       0.90      0.80      0.85        35
           8       0.83      0.77      0.80        26
           9       0.87      0.90      0.89        30

    accuracy                           0.76       281
   macro avg       0.77      0.77      0.76       281
weighted avg       0.77      0.76      0.76       281

 KERAS SEQUENTIAL/NN MODEL

In [89]:
# Create the Keras Sequential model
nn_model = tf.keras.models.Sequential()

In [90]:
# Add our first Dense layer, including the input layer
nn_model.add(tf.keras.layers.Dense(units=20, activation="relu"))

In [91]:
# Add our first Dense layer, including the input layer
nn_model.add(tf.keras.layers.Dense(units=15, activation="sigmoid"))

In [92]:
# Add the output layer that uses a probability activation function
nn_model.add(tf.keras.layers.Dense(units=10, activation="linear"))

In [95]:
# Check the structure of the Sequential model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 20)                5820

 dense_4 (Dense)             (None, 15)                315

 dense_5 (Dense)             (None, 10)                160

=================================================================
Total params: 6,295
Trainable params: 6,295
Non-trainable params: 0
_________________________________________________________________

In [94]:
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=['mse'])

# Fit the model to the training data
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
27/27 [==============================] - 1s 1ms/step - loss: 33.5933 - mse: 29.9446
Epoch 2/100
27/27 [==============================] - 0s 2ms/step - loss: 23.4052 - mse: 28.7504
Epoch 3/100
27/27 [==============================] - 0s 2ms/step - loss: 8.8921 - mse: 27.3793
Epoch 4/100
27/27 [==============================] - 0s 1ms/step - loss: -1.2189 - mse: 26.2871
Epoch 5/100
27/27 [==============================] - 0s 2ms/step - loss: -4.0547 - mse: 25.5859
Epoch 6/100
27/27 [==============================] - 0s 1ms/step - loss: -5.8587 - mse: 25.0054
Epoch 7/100
27/27 [==============================] - 0s 1ms/step - loss: -9.2749 - mse: 24.3774
Epoch 8/100
27/27 [==============================] - 0s 2ms/step - loss: -13.1605 - mse: 23.7919
Epoch 9/100
27/27 [==============================] - 0s 1ms/step - loss: -16.4797 - mse: 23.4131
Epoch 10/100
27/27 [==============================] - 0s 2ms/step - loss: -18.1873 - mse: 23.1292
Epoch 11/100
27/27 [==============================] - 0s 2ms/step - loss: -20.7663 - mse: 22.8425
Epoch 12/100
27/27 [==============================] - 0s 1ms/step - loss: -22.0609 - mse: 22.5577
Epoch 13/100
27/27 [==============================] - 0s 2ms/step - loss: -22.3490 - mse: 22.4597
Epoch 14/100
27/27 [==============================] - 0s 2ms/step - loss: -22.6209 - mse: 22.3888
Epoch 15/100
27/27 [==============================] - 0s 1ms/step - loss: -23.0014 - mse: 22.2973
Epoch 16/100
27/27 [==============================] - 0s 2ms/step - loss: -25.0170 - mse: 22.1445
Epoch 17/100
27/27 [==============================] - 0s 1ms/step - loss: -27.5275 - mse: 21.9826
Epoch 18/100
27/27 [==============================] - 0s 1ms/step - loss: -27.9166 - mse: 21.9050
Epoch 19/100
27/27 [==============================] - 0s 2ms/step - loss: -28.1178 - mse: 21.8241
Epoch 20/100
27/27 [==============================] - 0s 1ms/step - loss: -28.2655 - mse: 21.7539
Epoch 21/100
27/27 [==============================] - 0s 1ms/step - loss: -28.3705 - mse: 21.7297
Epoch 22/100
27/27 [==============================] - 0s 1ms/step - loss: -28.4559 - mse: 21.7158
Epoch 23/100
27/27 [==============================] - 0s 1ms/step - loss: -28.5212 - mse: 21.7044
Epoch 24/100
27/27 [==============================] - 0s 2ms/step - loss: -28.5908 - mse: 21.7101
Epoch 25/100
27/27 [==============================] - 0s 2ms/step - loss: -28.6208 - mse: 21.7074
Epoch 26/100
27/27 [==============================] - 0s 2ms/step - loss: -28.7017 - mse: 21.6692
Epoch 27/100
27/27 [==============================] - 0s 1ms/step - loss: -28.7319 - mse: 21.6567
Epoch 28/100
27/27 [==============================] - 0s 1ms/step - loss: -28.7370 - mse: 21.6220
Epoch 29/100
27/27 [==============================] - 0s 1ms/step - loss: -28.7676 - mse: 21.6033
Epoch 30/100
27/27 [==============================] - 0s 2ms/step - loss: -28.7884 - mse: 21.6134
Epoch 31/100
27/27 [==============================] - 0s 1ms/step - loss: -28.7982 - mse: 21.6189
Epoch 32/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8080 - mse: 21.6263
Epoch 33/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8175 - mse: 21.6246
Epoch 34/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8172 - mse: 21.6359
Epoch 35/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8250 - mse: 21.6497
Epoch 36/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8522 - mse: 21.6538
Epoch 37/100
27/27 [==============================] - 0s 2ms/step - loss: -28.8023 - mse: 21.7537
Epoch 38/100
27/27 [==============================] - 0s 1ms/step - loss: -28.7706 - mse: 21.7461
Epoch 39/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8530 - mse: 21.6291
Epoch 40/100
27/27 [==============================] - 0s 2ms/step - loss: -28.8612 - mse: 21.5425
Epoch 41/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8703 - mse: 21.5015
Epoch 42/100
27/27 [==============================] - 0s 1ms/step - loss: -28.8988 - mse: 21.4962
Epoch 43/100
27/27 [==============================] - 0s 1ms/step - loss: -28.9080 - mse: 21.4861
Epoch 44/100
27/27 [==============================] - 0s 1ms/step - loss: -28.9247 - mse: 21.4728
Epoch 45/100
27/27 [==============================] - 0s 2ms/step - loss: -28.9408 - mse: 21.4637
Epoch 46/100
27/27 [==============================] - 0s 1ms/step - loss: -28.9488 - mse: 21.4278
Epoch 47/100
27/27 [==============================] - 0s 1ms/step - loss: -28.9584 - mse: 21.4322
Epoch 48/100
27/27 [==============================] - 0s 1ms/step - loss: -28.9692 - mse: 21.4421
Epoch 49/100
27/27 [==============================] - 0s 1ms/step - loss: -28.9870 - mse: 21.4591
Epoch 50/100
27/27 [==============================] - 0s 2ms/step - loss: -29.0058 - mse: 21.4796
Epoch 51/100
27/27 [==============================] - 0s 1ms/step - loss: -29.0183 - mse: 21.4697
Epoch 52/100
27/27 [==============================] - 0s 1ms/step - loss: -29.0381 - mse: 21.4074
Epoch 53/100
27/27 [==============================] - 0s 1ms/step - loss: -29.0474 - mse: 21.4124
Epoch 54/100
27/27 [==============================] - 0s 1ms/step - loss: -29.0712 - mse: 21.4293
Epoch 55/100
27/27 [==============================] - 0s 1ms/step - loss: -29.0732 - mse: 21.4587
Epoch 56/100
27/27 [==============================] - 0s 1ms/step - loss: -29.1053 - mse: 21.4700
Epoch 57/100
27/27 [==============================] - 0s 2ms/step - loss: -29.1164 - mse: 21.4916
Epoch 58/100
27/27 [==============================] - 0s 1ms/step - loss: -29.1175 - mse: 21.5601
Epoch 59/100
27/27 [==============================] - 0s 1ms/step - loss: -29.1355 - mse: 21.5678
Epoch 60/100
27/27 [==============================] - 0s 1ms/step - loss: -29.1593 - mse: 21.5590
Epoch 61/100
27/27 [==============================] - 0s 1ms/step - loss: -29.1894 - mse: 21.5657
Epoch 62/100
27/27 [==============================] - 0s 1ms/step - loss: -29.2131 - mse: 21.5746
Epoch 63/100
27/27 [==============================] - 0s 1ms/step - loss: -29.2188 - mse: 21.5998
Epoch 64/100
27/27 [==============================] - 0s 2ms/step - loss: -29.2354 - mse: 21.6133
Epoch 65/100
27/27 [==============================] - 0s 1ms/step - loss: -29.2701 - mse: 21.6354
Epoch 66/100
27/27 [==============================] - 0s 1ms/step - loss: -29.2848 - mse: 21.6504
Epoch 67/100
27/27 [==============================] - 0s 1ms/step - loss: -29.2828 - mse: 21.6708
Epoch 68/100
27/27 [==============================] - 0s 1ms/step - loss: -29.2960 - mse: 21.6378
Epoch 69/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3035 - mse: 21.6572
Epoch 70/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3064 - mse: 21.6645
Epoch 71/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3144 - mse: 21.6552
Epoch 72/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3311 - mse: 21.6701
Epoch 73/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3361 - mse: 21.6615
Epoch 74/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3346 - mse: 21.6404
Epoch 75/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3274 - mse: 21.5957
Epoch 76/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3150 - mse: 21.4906
Epoch 77/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3308 - mse: 21.4708
Epoch 78/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3455 - mse: 21.5013
Epoch 79/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3637 - mse: 21.5473
Epoch 80/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3687 - mse: 21.5429
Epoch 81/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3144 - mse: 21.4379
Epoch 82/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3278 - mse: 21.4504
Epoch 83/100
27/27 [==============================] - 0s 2ms/step - loss: -29.1828 - mse: 21.5125
Epoch 84/100
27/27 [==============================] - 0s 1ms/step - loss: -29.0349 - mse: 21.5678
Epoch 85/100
27/27 [==============================] - 0s 2ms/step - loss: -29.2260 - mse: 21.4930
Epoch 86/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3248 - mse: 21.4480
Epoch 87/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3457 - mse: 21.4510
Epoch 88/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3540 - mse: 21.4575
Epoch 89/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3733 - mse: 21.4661
Epoch 90/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3714 - mse: 21.4883
Epoch 91/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3782 - mse: 21.4800
Epoch 92/100
27/27 [==============================] - 0s 2ms/step - loss: -29.4018 - mse: 21.4522
Epoch 93/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3942 - mse: 21.4493
Epoch 94/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3966 - mse: 21.3049
Epoch 95/100
27/27 [==============================] - 0s 1ms/step - loss: -29.3833 - mse: 21.2581
Epoch 96/100
27/27 [==============================] - 0s 2ms/step - loss: -29.3897 - mse: 21.2634
Epoch 97/100
27/27 [==============================] - 0s 1ms/step - loss: -29.4016 - mse: 21.2605
Epoch 98/100
27/27 [==============================] - 0s 1ms/step - loss: -29.4130 - mse: 21.2646
Epoch 99/100
27/27 [==============================] - 0s 1ms/step - loss: -29.4246 - mse: 21.2710
Epoch 100/100
27/27 [==============================] - 0s 1ms/step - loss: -29.4294 - mse: 21.2820

In [98]:
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

9/9 - 0s - loss: -2.9118e+01 - mse: 22.1751 - 397ms/epoch - 44ms/step
Loss: -29.118114471435547, Accuracy: 22.17507553100586

 AUTO-OPTIMIZED MODEL THAT FINDS THE TOP MODELS

In [96]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=10,
        step=2), activation=activation, input_dim=2))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=10,
            step=2),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["mse"])
    
    return nn_model

In [97]:
! pip install keras_tuner 
import keras_tuner as kt
from tensorflow.keras import layers

class CustomMetric(keras.metrics.Metric):
    def __init__(self, **kwargs):
        # Specify the name of the metric as "custom_metric".
        super().__init__(name="custom_metric", **kwargs)
        self.sum = self.add_weight(name="sum", initializer="zeros")
        self.count = self.add_weight(name="count", dtype=tf.int32, initializer="zeros")

    def update_state(self, y_true, y_pred, sample_weight=None):
        y_true = tf.cast(y_true, dtype=tf.float32 , name=None)
        values = tf.math.squared_difference(y_pred, y_true)
        count = tf.shape(y_true)[0]
        if sample_weight is not None:
            sample_weight = tf.cast(sample_weight, self.dtype)
            values *= sample_weight
            count *= sample_weight
        self.sum.assign_add(tf.reduce_sum(values))
        self.count.assign_add(count)

    def result(self):
        return self.sum / tf.cast(self.count, tf.float32)

    def reset_states(self):
        self.sum.assign(0)
        self.count.assign(0)



def build_regressor(hp):
    model = keras.Sequential(
        [
            layers.Dense(units=hp.Int("units", 100, 10000, 10), activation="relu"),
            layers.Dense(units=hp.Int("units", 10, 1000, 10), activation="tanh"),
            layers.Dense(units=1),
        ]
    )
    model.compile(
        optimizer="adam",
        loss="mean_squared_error",
        # Put custom metric into the metrics.
        metrics=[CustomMetric()],
    )
    return model


tuner = kt.RandomSearch(
    hypermodel=build_regressor,
    # Specify the name and direction of the objective.
    objective=kt.Objective("val_custom_metric", direction="min"),
    max_trials=20,
    overwrite=True,
    directory="my_dir",
    project_name="custom_metrics",
)

tuner.search(
    x=X_train_scaled,
    y=y_train,
    validation_data=(X_test_scaled,y_test)
)

tuner.results_summary()

Trial 20 Complete [00h 00m 28s]
val_custom_metric: 8.597326278686523

Best val_custom_metric So Far: 1.2914750576019287
Total elapsed time: 00h 04m 22s
Results summary
Results in my_dir/custom_metrics
Showing 10 best trials
Objective(name="val_custom_metric", direction="min")

Trial 08 summary
Hyperparameters:
units: 340
Score: 1.2914750576019287

Trial 13 summary
Hyperparameters:
units: 1980
Score: 3.024329662322998

Trial 06 summary
Hyperparameters:
units: 1850
Score: 3.150338649749756

Trial 11 summary
Hyperparameters:
units: 1480
Score: 3.250936985015869

Trial 07 summary
Hyperparameters:
units: 6640
Score: 3.4685451984405518

Trial 09 summary
Hyperparameters:
units: 1910
Score: 3.702943801879883

Trial 18 summary
Hyperparameters:
units: 7660
Score: 3.9220669269561768

Trial 12 summary
Hyperparameters:
units: 2240
Score: 4.812060832977295

Trial 02 summary
Hyperparameters:
units: 3000
Score: 5.429911136627197

Trial 16 summary
Hyperparameters:
units: 7460
Score: 5.437463283538818

LINEAR

In [99]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [100]:
model.fit(X, y)

LinearRegression()

In [101]:
predicted_y_values = model.predict(X)

In [102]:
!pip install tensorflow_addons

import tensorflow_addons as tfa

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tensorflow_addons in /usr/local/lib/python3.10/dist-packages (0.20.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow_addons) (23.1)
Requirement already satisfied: typeguard<3.0.0,>=2.7 in /usr/local/lib/python3.10/dist-packages (from tensorflow_addons) (2.13.3)

In [103]:
from sklearn.metrics import mean_squared_error, r2_score
r2 = r2_score(y, predicted_y_values)

r2

0.9379204167987443